### ISSUE TITLE
Not changing shows or movies

### ISSUE THREAD

**Issue by BmanGames024** [Ombrelin/plex-rich-presence#34]
So when you do a fresh boot of the app ti works but after a few switching the app will lose track of where u were so it will just say you have 0 seconds on the item your watching or not even say your watching the correct thing

**Comment by mclarence** [comment]
Please download the latest .jar file instead of the windows/exe one and run the following in cmd:

"C:\Program Files (x86)\Plex Rich Presence\jre\bin\java.exe" -jar <path to downloaded jar file> -Dlogging.level.root=DEBUG , reproduce the issue and post the debug log here. 

>  few switching the app
Please clarify what you mean by this.
