### ISSUE TITLE
Include the name of the played movie or series in the status

### ISSUE THREAD

**Issue by AaronWiora** [Ombrelin/plex-rich-presence#48]
Would it be possible to show the played movie or tv-show directly in the status message?
Instead of "_Playing Plex_" it would be "_is watching 'The Office_'".
This way, people who are to lazy to click on the status (or don't know this is an option) will know what is being played.

Discord added the option so set a custom status some time ago but does the API allow applications to change it?

**Comment by AaronWiora** [comment]
Now that I think about it: Spotify also doesn't show the song that is played so maybe this is the gold standard. So maybe this issue can be closed.

**Comment by Ombrelin** [comment]
Hello,

sadly, the rich presence API does not offer this capability. I have no ability to control the text displayed in the "Playing XXX" mention at runtime, since it display the name of the application that I have registered on discord's dev platform to be able to use the API. The rich presence API was originally designed for games that's it shows "playing" which believe me I would have replaced galdly with "Listening" or "Watching" if I could

**Comment by Ombrelin** [comment]
Yes and even Spotify can do thing that I can't (like display the song progress bar) so I think they have a special partnership with discord for that

**Comment by Ombrelin** [comment]
I will then close this issue for now, but let's hope some day discord will update the rich presence API to be more friendly with non-game usages

**Comment by indianpoptart** [comment]
Hey, I know you are using a java lib for the RPC, but after some digging, it seems they have an [ActivityType enum to their GameSDK](https://discord.com/developers/docs/game-sdk/activities#data-models-activitytype-enum)

I assume this would require a rewrite since RPC is deprecated [GameSDK](https://discord.com/developers/docs/game-sdk/sdk-starter-guide)

**Comment by Ombrelin** [comment]
Hey ! That's really intersting. I plan to do a rewrite anyway using .NET, so I'll definetly look into the GameSDK.
Thank you for bringing that to my attention !
I plan to start the rewrite by august, I'll keep you posted.

**Comment by indianpoptart** [comment]
That's awesome! I'll see if I can find any .NET related documentation for GameSDK and let you know what I find. 

Cheers!
