### ISSUE TITLE
[Enhancement] Support managed users

### ISSUE THREAD

**Issue by jensengillett** [Ombrelin/plex-rich-presence#68]
My current Plex setup has a main account with managed users attached to it so that individual people can have their own separate watch history, home page, etc. 
I use one of the managed users for my playback generally, and when I stream something off that account the application doesn't pick it up; but if I switch to the main user and play something there, it picks it up just fine. 
I'm guessing this isn't a bug, there just isn't currently a way to select a managed user after logging in with the main account, thus it only picks up sessions from the primary user. Is this something that could be supported in the future?

**Comment by Ombrelin** [comment]
Hello, on the current version of the app, only the main account is supported because the "session" endpoint of the plex api is used, which is only accessible to the owner of the server.
However i'm currently working on a rewrite of the app with better technology and plan to use plex websocket api to capture activity, which should work for any user.

**Comment by Ombrelin** [comment]
I added mention of your feature in the discussing about the rewrite

**Comment by Ombrelin** [comment]
Should be fixed in 2.0 version !
