### ISSUE TITLE
Reconnect Upon Wake

### ISSUE THREAD

**Issue by cbtlr** [Ombrelin/plex-rich-presence#95]
I have my server information entered manually because the automatic server selection is a bit of a mess - it's showing the same library many times all under different addresses.

When I sleep the computer and rewake it, it can't connect, and doesn't seem to retry to connect - but restarting the application addresses it.

**Comment by Ombrelin** [comment]
> I have my server information entered manually because the automatic server selection is a bit of a mess - it's showing the same library many times all under different addresses.
This behaviour is most likely due to old data about your server being present on your PLEX account. I don't control that, but you can clean it in your PLEX account management UI in the PLEX app.

> When I sleep the computer and rewake it, it can't connect, and doesn't seem to retry to connect - but restarting the application addresses it.
Could you provide me the logs of the app ? Present under `<your user directory>/.plexrichpresence`. Does it still happens with last release ? I've introduced fixed which could be related to that error.

**Comment by Ombrelin** [comment]
Closing for now since no feedback, reopen if needed
